### PR TITLE
Change environment to Codespace

### PR DESCRIPTION
**Pull request by grantcarthew**

### CODE REVIEW

**Comment by grantcarthew** [comment]
Hi @GraemeMalcolm 

I went to the page in the lab and it has a large button labelled "Create Codespace". I gather it changed from create environment.

The fact that you are closing this PR with no comment means I am wrong I gather. I'll have a closer look next time it is in my scope.

**Comment by GraemeMalcolm** [comment]
The lab doc was updated a few days ago - pull the latest version.

**Comment by grantcarthew** [comment]
Hi @GraemeMalcolm, this isn't fixed. I'm teaching it this week and next week.

**Comment by GraemeMalcolm** [comment]
Sorry - thought I'd caught this - try now.

**Pull request closed without merging**
